### ISSUE TITLE
Crashes a lot when doing different operations

### ISSUE THREAD

**Issue by shipsywor** [llastkrakw/NeverNote#1]
**When selecting the blue link button:**

```
19426-19426/com.llastkrakw.nevernote E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.llastkrakw.nevernote, PID: 19426
    java.lang.IndexOutOfBoundsException: getChars (-1 ... -1) starts before 0
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1330)
        at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1205)
        at android.text.TextUtils.getChars(TextUtils.java:154)
        at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:68)
        at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1197)
        at com.llastkrakw.nevernote.views.notes.activities.AddNoteActivity$enableStyle$$inlined$apply$lambda$8.onClick(AddNoteActivity.kt:189)
```

**When selecting colors:**

```
20505-20505/com.llastkrakw.nevernote E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.llastkrakw.nevernote, PID: 20505
    java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
        at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:496)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:196)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:183)
        at android.text.SpannableString.setSpan(SpannableString.java:60)
        at com.llastkrakw.nevernote.core.utilities.SpanUtilsKt.span(SpanUtils.kt:39)
        at com.llastkrakw.nevernote.core.utilities.SpanUtilsKt.setColor(SpanUtils.kt:60)
        at com.llastkrakw.nevernote.core.utilities.Editor.setColor(Editor.kt:238)
        at com.llastkrakw.nevernote.views.notes.activities.AddNoteActivity$enableStyle$$inlined$apply$lambda$7$1.invoke(AddNoteActivity.kt:182)
        at com.llastkrakw.nevernote.views.notes.activities.AddNoteActivity$enableStyle$$inlined$apply$lambda$7$1.invoke(AddNoteActivity.kt:44)
```

**Unsplash search does not work even when api key and secret is added**

Nothing shows up.

**When A+ button is selected**

```
 24512-24512/com.llastkrakw.nevernote E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.llastkrakw.nevernote, PID: 24512
    java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
        at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:496)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:196)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:183)
        at android.text.SpannableString.setSpan(SpannableString.java:60)
        at com.llastkrakw.nevernote.core.utilities.SpanUtilsKt.span(SpanUtils.kt:39)
        at com.llastkrakw.nevernote.core.utilities.SpanUtilsKt.size(SpanUtils.kt:58)
        at com.llastkrakw.nevernote.core.utilities.Editor.increaseSize(Editor.kt:234)
        at com.llastkrakw.nevernote.views.notes.activities.AddNoteActivity$enableStyle$$inlined$apply$lambda$4.onClick(AddNoteActivity.kt:166)
```

Please fix the issues. Thank you

**Comment by llastkrakw** [comment]
thanks for reply, you probably didn't select a text , I shall add the condition for these. for unsplah select clothes  icon and select the image.

**Comment by llastkrakw** [comment]
now i fixed the issues , check the latest app, thanks
